src/objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Picture_Path__c</fullName>
        <label>Picture Path</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP={00000}</displayFormat>
        <label>Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SpeakerControllerExtension.cls
/**
 * Created by miler_8zu3w9c on 7/13/2017.
 */
public with sharing class SpeakerControllerExtension {
	private final Speaker__c speaker;

	public Blob picture {get;set;}
	public String errorMessage {get;set;}

	private ApexPages.StandardController standardController;

	public SpeakerControllerExtension(ApexPages.StandardController standardController){
		this.speaker = (Speaker__c) standardController.getRecord();
		this.standardController = standardController;
	}

	public PageReference save(){
		errorMessage = '';
		try{
			upsert speaker;
			if(picture != null){
				Attachment attachment = new Attachment();
				attachment.Body = picture;
				attachment.Name = 'speaker_' + speaker.Id + '.jpg';
				attachment.ParentId = speaker.Id;
				attachment.ContentType = 'application/jpg';
				insert attachment;
				speaker.Picture_Path__C = '/servlet/servlet.FileDownload?file=' + attachment.Id;
				update  speaker;
			}
			return new ApexPages.StandardController(speaker).view();
		}catch (System.Exception ex){
			errorMessage = ex.getMessage();
			return null;
		}
	}


}