src/objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SP={00000}</displayFormat>
        <label>Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendReminderEmail.cls
/**
 * Created by miler_8zu3w9c on 7/13/2017.
 */
global class SendReminderEmail implements Database.Batchable<sObject>{

	global String query;
	global String subject;
	global String body;


	global SendReminderEmail(String query, String subject, String body) {
		this.query = query;
		this.subject = subject;
		this.body = body;
	}

	public System.Iterable<sObject> start(Database.BatchableContext jobId) {
		return Database.getQueryLocator(query);
	}

	public Void execute(Database.BatchableContext jobId, List<Speaker__c> scope) {
		for(Speaker__c speaker : scope){
			EmailManager.sendMail(speaker.Email__c, this.subject, this.body);
		}
	}

	public Void finish(Database.BatchableContext jobId) {
	}

}